### PR TITLE
Issue #64 Favicon

### PR DESCRIPTION
**Pull request by indydedeken**
add favicon

### CODE REVIEW

**Comment by Yoric** [comment]
This looks good, thanks. I confirm that it works in Firefox. Do you have a chance to test it with IE, by any chance?

**Comment by indydedeken** [comment]
I can't but @BragaLuis is testing it.

**Comment by BragaLuis** [comment]
This is not working on IE, we also try to change PNG to ICO : `<link rel="shortcut icon" type="image/x-icon" href="img/icon60.ico" />`, and it's not working either

**Comment by Yoric** [comment]
Let's open a new bug for IE.

**Pull request merged**
