### PR TITLE
Issue #138 Add a variable in 'Config'

### PR DESCRIPTION
**Pull request by fatimzahara**
Add a variable in 'Config' to determine whether we should go to
fullscreen.

### CODE REVIEW

**Comment by Yoric** [comment]
The commit is good, but I can't pull it as it conflicts with a commit I just landed.
Can you pull the latest version of the source code and fix the conflict?

**Comment by fatimzahara** [comment]
ok

**Comment by fatimzahara** [comment]
@Yoric may I do a pull request after the merge of fixing the conflict ??

**Comment by Yoric** [comment]
Yes, please.

**Pull request closed without merging**
