### PR TITLE
fix issue #114

### PR DESCRIPTION
**Pull request by pfautrero**
Retrieve title attribute from HTMLDocument instead of head title tag (not reliable)

### CODE REVIEW

**Comment by Yoric** [comment]
It looks to me like we could directly use `xml.title`. Have you tried that?

**Comment by pfautrero** [comment]
sure ! You are right. You fix it yourself or you need new pull request ?

**Comment by pfautrero** [comment]
so, I updated the pull request just for review. I added the #129 issue in this pull request.

**Comment by Yoric** [comment]
Have you tested that `"application/xhtml+xml"` doesn't break any of the books in the `samples/` directory?

Also, please fold your patches in a single patch.

**Comment by pfautrero** [comment]
hum...merging commits already pushed is not so easy for me :) I close this pull request to submit new one. I tested on xml based ebooks. For html ones, it is not working. In the next pull request, I add a mimetype selector based on file extension.

**Comment by Yoric** [comment]
To fold a commit that is already pushed to _your_ repo, do the following:
- `git rebase --interactive HEAD~7`  (this is for editing up to `7` commits, you may of course change the number);
- this will open an editor, look at the documentation in the bottom – you need to use `fixup` to fold the commits;
- finally, `git push -f` will _overwrite_ your repo.

**Comment by pfautrero** [comment]
haaaa ! great ! fixup and push -f !! I used squash and push without -f arg...Thanks !

**Pull request closed without merging**
